### ISSUE TITLE
Testing: 3.1.2

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#1010]
Relevant code is the up-to-date master branch.

This is a bugfix release so not really major changes but there's a few things to look for:

- A cleanup of the admin theme styles means some existing styles that were getting overridden now take effect. 3.1.1 and older have a style that sets the font and size of all elements, meaning that styles which try to do things like change the size on a container assuming it will affect the children inside weren't working. The obvious places where this caused issues have been caught but there could be others, particularly in plugins.
- As part of this there's some purposeful style changes and/or restorations of prior styling. One obvious part of that is the login form: the fields now (as in older versions) appear on the same line with their labels). Another is that the "explanation" text for fields was somewhat oddly larger than almost all other text; it's now the same size.
- The bug we'd previously found where the download button on the lightgallery viewer on the public side didn't work should be fixed in this version
- The login page and the installer form were slightly broken since the new admin theme: they weren't displaying the form errors. This should be fixed so errors like leaving required fields blank are now reported next to the problematic field, as in pre-3.0.
- Most of the rest of it is invisible bug fixes and cleaning up logged notices

**Comment by allanaaa** [comment]
Everything seems good that I can see, all interface display stuff. Login form seems good, errors seem good. Things look good in a few public themes.
 
I can start a new install if you want me to check that form. Or I can install Lightbox if you need me to test the downlaod button. Otherwise I imagine things are fine. 

What's the primary time-sensitive reason for releasing this version? I assume some specific bug fix? I don't see anything to do documentation-wise.

**Comment by zerocrates** [comment]
Just bug fixes more or less. A few people have current issues with some things that this release would fix, mostly things from newer PHP and MySQL versions.
