### ISSUE TITLE
Testing: Add multiple files in one action

### ISSUE THREAD

**Issue by jimsafley** [omeka/Omeka#1018]
The [multiple-file-input](https://github.com/omeka/Omeka/tree/multiple-file-input) branch allows users to add multiple files in one action. There are two ways to do this:

- Click on the "Choose files" button and select more than one file using shift+click or ctrl+click
- Drag-and-drop files onto the "Choose files" button.

Once added, the file inputs should contain the file size and a thumbnail (for browser-compatible images). Make sure all files are uploaded.

**Comment by katknow** [comment]
For the most part this seems to be working! The one thing is that images are the only thumbnail that see to appear prior to pressing save (and this is the same across browsers):

![image](https://github.com/omeka/Omeka/assets/84726696/3bdf8157-b768-4882-9fe8-6d67a9295c6f)

However, all render perfectly fine after saving.

For dragging the files to "Browse", you just have to be careful because if I accidentally was over "Add Another File" too long it just opened all the files in my browser and took me away from the page.

**Comment by kimisgold** [comment]
That's all as expected. We don't create file derivatives on upload: those come after saving the form, so we can only provide previews for files the browser can render. Looks good then!
