### ISSUE TITLE
Tags do not work when there are comma's

### ISSUE THREAD

**Issue by misilot** [omeka/Omeka#660]
For example:

site/admin/items/?tag=Johnson,%20Seward,%20-1983

Returns no results, however on the Edit Tags page, it says there are 4 items.

I am running Omeka v2.2.2

**Comment by zerocrates** [comment]
The default "tag delimiter" is a comma, so most places in Omeka will treat a string with commas in it as multiple different tags.

If you have tags with commas (say, because they've been imported), you can change the tag delimiter to some other character you're not using (maybe the `|` pipe character, for example) in Settings -> General -> Tag Delimiter.
