### ISSUE TITLE
SSL test in bootstrap.php not necessarily working

### ISSUE THREAD

**Issue by anuragji** [omeka/Omeka#685]
I was deploying an Omeka website on a server running PHP 5.5.29 and Apache 2.4.16. I was initially getting SSL errors because the paths did not get switched correctly. Upon further investigation it turned out that my `$_SERVER` vars did not contain `HTTPS`, but instead `HTTP_X_FORWARDED_PROTO` was used to indicate the type of http connection.

So I updated `bootstrap.php` from:
`$base_root = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https' : 'http';`
to
`$base_root = (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') ? 'https' : 'http';`

Now the paths are set correctly.

I am not an expert on Apache, but I guess that this might not be as uncommon, so perhaps  the out-of-the-box `bootstrap.php` should test for either.

**Comment by zerocrates** [comment]
That seems pretty reasonable, to have this check for X-Forwarded-Proto in addition... I can't think of any problem it would cause.

**Comment by anuragji** [comment]
I have created a pull-request for the issue.

**Comment by zerocrates** [comment]
I'm not seeing a pull request.

**Comment by anuragji** [comment]
Sorry, I just updated it.

**Comment by zerocrates** [comment]
My one concern is that this seems like it's likely to mess up the port detection part of the file below. If there's a proxy that's switching the protocol, then presumably the "real" connection from Omeka's perspective (the one between the proxy and Omeka) is happening on port 80 (or some other port, anyway), and we will see that we're producing https URLs and the port isn't 443, and therefore add the port to the base URL when we shouldn't.

It seems to me that we need to detect if we're paying attention to X-Forwarded-Proto, and if we are, then also use X-Forwarded-Port (or just default to 443 if we're doing https because of X-Forwarded-Proto).

Have you seen any issues with the port in the URL since making your change?

**Comment by anuragji** [comment]
I have not seen any issue with the port settings, but let me take a more detailed look. However, it seems reasonable to assume that the port should be detected in a similar fashion using X-Forwarded-Proto. I'll take a detailed look at what _$_SERVER_ contains.

**Comment by anuragji** [comment]
I realized I never responded. I have been using the fix I created in my pull request for several weeks now (and on several different sites) and it is working without any errors. But I am using the default ports - 80 / 443. 

For good measure, here is an excerpt of `$_SERVER` for both HTTPS and HTTP requests:

`$_SERVER` HTTP:

    'forwarded' => string '1' (length=1)
    'HTTP_ACCEPT' => string 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' (length=74)
    'HTTP_UPGRADE_INSECURE_REQUESTS' => string '1' (length=1)
    'HTTP_USER_AGENT' => string 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36' (length=121)
    'HTTP_ACCEPT_ENCODING' => string 'gzip, deflate, sdch' (length=19)
    'HTTP_ACCEPT_LANGUAGE' => string 'en-US,en;q=0.8,de;q=0.6' (length=23)
    'HTTP_X_FORWARDED_PROTO' => string 'http' (length=4)
    'HTTP_X_FORWARDED_PORT' => string '80' (length=2)
    'HTTP_X_APPLE_SERVICE_WEBCALSSL_ENABLED' => string 'true' (length=4)
    'HTTP_X_APPLE_SERVICE_PROFILE_MANAGER_ENABLED' => string 'true' (length=4)
    'HTTP_X_FORWARDED_FOR' => string '192.168.1.1' (length=11)
    'HTTP_X_FORWARDED_HOST' => string 'digark.info' (length=11)
    'HTTP_X_FORWARDED_SERVER' => string 'digark6.local' (length=13)
    'HTTP_CONNECTION' => string 'Keep-Alive' (length=10)
    'PATH' => string '/usr/bin:/bin:/usr/sbin:/sbin' (length=29)
    'SERVER_SIGNATURE' => string '<address>Apache Server at digark.info Port 80</address>' (length=56)
    'SERVER_SOFTWARE' => string 'Apache' (length=6)
    'SERVER_NAME' => string 'digark.info' (length=11)
    'SERVER_ADDR' => string '127.0.0.1' (length=9)
    'SERVER_PORT' => string '80' (length=2)
    'REMOTE_ADDR' => string '127.0.0.1' (length=9)
    'REQUEST_SCHEME' => string 'http' (length=4)
    'CONTEXT_PREFIX' => string '' (length=0)
    'REMOTE_PORT' => string '61468' (length=5)
    'GATEWAY_INTERFACE' => string 'CGI/1.1' (length=7)
    'SERVER_PROTOCOL' => string 'HTTP/1.1' (length=8)
    'REQUEST_METHOD' => string 'GET' (length=3)
    'QUERY_STRING' => string '' (length=0)
    'REQUEST_URI' => string '/info.php' (length=9)
    'SCRIPT_NAME' => string '/info.php' (length=9)
    'PHP_SELF' => string '/info.php' (length=9)
  
`$_SERVER` HTTPS:

    'forwarded' => string '1' (length=1)
    'RETP_ACCEPT' => string 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' (length=74)
    'RETP_UPGRADE_INSECURE_REQUESTS' => string '1' (length=1)
    'RETP_USER_AGENT' => string 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36' (length=121)
    'RETP_ACCEPT_ENCODING' => string 'gzip, deflate, sdch' (length=19)
    'RETP_ACCEPT_LANGUAGE' => string 'en-US,en;q=0.8,de;q=0.6' (length=23)
    'RETP_X_FORWARDED_PROTO' => string 'https' (length=5)
    'RETP_X_FORWARDED_PORT' => string '443' (length=3)
    'RETP_X_FORWARDED_FOR' => string '192.168.1.1' (length=11)
    'RETP_X_FORWARDED_HOST' => string 'digark.info' (length=11)
    'RETP_X_FORWARDED_SERVER' => string 'digark.info' (length=11)
    'RETP_CONNECTION' => string 'Keep-Alive' (length=10)
    'PATH' => string '/usr/bin:/bin:/usr/sbin:/sbin' (length=29)
    'SERVER_SIGNATURE' => string '<address>Apache Server at digark.info Port 443</address>' (length=57)
    'SERVER_SOFTWARE' => string 'Apache' (length=6)
    'SERVER_NAME' => string 'digark.info' (length=11)
    'SERVER_ADDR' => string '127.0.0.1' (length=9)
    'SERVER_PORT' => string '443' (length=3)
    'REMOTE_ADDR' => string '127.0.0.1' (length=9)
    'REQUEST_SCHEME' => string 'https' (length=5)
    'CONTEXT_PREFIX' => string '' (length=0)
    'REMOTE_PORT' => string '61366' (length=5)
    'GATEWAY_INTERFACE' => string 'CGI/1.1' (length=7)
    'SERVER_PROTOCOL' => string 'HTTP/1.1' (length=8)
    'REQUEST_METHOD' => string 'GET' (length=3)
    'QUERY_STRING' => string '' (length=0)
    'REQUEST_URI' => string '/info.php' (length=9)
    'SCRIPT_NAME' => string '/info.php' (length=9)
    'PHP_SELF' => string '/info.php' (length=9)`

**Comment by zerocrates** [comment]
It's interesting that the SERVER_PORT and REQUEST_SCHEME are consistent with HTTPS. That would seem to indicate that the "internal" request is actually using https, which should work. And yet, even so, the HTTPS server-var is missing. Anyway, the fact that those, in particular SERVER_PORT, are correct are the reason why you didn't need to look at X-Forwarded-Port.

Another oddity: in the HTTPS case, are all those variables actually "RETP_" instead of "HTTP_"? I've never seen that before.

This might actually just be some Apache configuration thing that's causing it not to set the HTTPS var, or something causing PHP to drop it. There's Zend Framework code that does the equivalent of this which looks at HTTPS, HTTP_SCHEME, and SERVER_PORT to try to detect an HTTPS connection. Doing that same thing in our bootstrap.php would look like the following, as a replacement for the existing `$base_root` one-liner:

```php
// Set the scheme.
if ((isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] === true))
    || (isset($_SERVER['HTTP_SCHEME']) && $_SERVER['HTTP_SCHEME'] == 'https')
    || (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
) {
    $base_root = 'https';
} else {
    $base_root = 'http';
}
```

Judging by the dumps you gave here, this change should work for you. I'd be more comfortable doing this version, just because it would stay in line with what Zend Framework's doing internally, so there's less chance for an annoying divergence where we detect HTTPS but Zend's code doesn't.

**Comment by anuragji** [comment]
"Another oddity: in the HTTPS case, are all those variables actually "RETP_" instead of "HTTP_"? I've never seen that before." No, thats pure user error :) I corrected the original dumps.

**Comment by zerocrates** [comment]
Can you confirm that the snippet I posted above solves your problem?

If so, then I'll make that change and close this issue.

**Comment by anuragji** [comment]
Yes, I can confirm that your snippet works on my server setup.

**Comment by zerocrates** [comment]
Thanks.
