### ISSUE TITLE
background processes and `background.php.path` on windows

### ISSUE THREAD

**Issue by tingletech** [omeka/Omeka#714]
There seems to be a bug with the way `background.php.path` deals with windows paths

![screen shot 2016-06-08 at 1 26 23 pm](https://cloud.githubusercontent.com/assets/227374/15909779/c2731d84-2d7c-11e6-8388-32eae1545f9e.png)

https://github.com/UCSCLibrary/NuxeoLink/issues/15

**Comment by zerocrates** [comment]
I'm pretty sure the problem is in how it treats spaces. We've had another report of this and a working solution was to precede the spaces with caret `^` characters, as that's a Windows escape character.

Still, we should handle the spaces correctly. It looks to me like we should be using `escapeshellarg` here instead of `escapeshellcmd`.

**Comment by zerocrates** [comment]
That change (12f6147df9087bcf693a74fdb24028a554bbc1b6) should make a space-containing path in background.php.path get handled correctly.

Autodetection isn't touched by this so it'd still have to be specified in the config.ini file to work. In this user's case, where their PHP CLI binary appears to be called "v5.6", there's no way we'd autodetect it anyway, even with a Windows-specific method.
