### ISSUE TITLE
Look over "batch edit all" branch

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#716]
The local branch is "batch-edit-all," an imported copy of #694.

That branch adds the ability to batch edit all items matching the current query, not just the current page's worth.

I'm looking for any and all feedback or ideas on it: the UI, the text, whether it matches your expectations, and of course anything you think is a bug.

**Comment by mebrett** [comment]
The "all" checkbox is showing up on admin/items, not just on the results of items/browse?search= (whatever). Which seems to imply that one could edit all the items in a site if you clicked the "all" box.

Visually, it's a bit crowded on the right by the quick filter dropdown. It's a little lost on that row because everything else is either a button or a dropdown with a stronger visual impact; even though it's the same font size, it looks smaller than the surrounding items. I also wonder if it might make sense to change the label to "select all results" or "All Results" to make it a little more evident what the box does.

Very good language on the batch edit page to make it clear what the user actions will do and that it might take a while.

**Comment by zerocrates** [comment]
> Which seems to imply that one could edit all the items in a site if you clicked the "all" box.

That should be the case, yes.

**Comment by zerocrates** [comment]
@kimisgold any ideas on the UI aspect?

I believe Daniel originally had it as a separate button rather than a checkbox, but that's got its own set of problems in terms of space, and we don't really have a lot of space available there. We'd probably have to move other existing stuff around to do much of anything with this.

**Comment by Daniel-KM** [comment]
Hi,

I pulled this request, because a lot of users display more than ten items and the batch edit fails in that case, so a background job is required. I didn't want to add a new page in a new plugin that clones the items/browse page. 

The button is too big and the check box is not understandable by end user (that's why I added a tool tip, but this is not enough). Another possibility is to add a checkbox beside the one in the header of the list or to change the behavior of this one. This is a better solution for me, because it does not weigh the interface, but the user should know that the process will be backgrounded.

Another issue is that the user don't know when the job is finished and if there are errors, because the log are readable only on the server.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by kimisgold** [comment]
I've revised the interface to give all the actions a little space, as well as to provide a tracker for how many results are currently selected for batch editing. Hopefully this is a clearer presentation of the feature that addresses the concerns outside of the background process status.

**Comment by Daniel-KM** [comment]
Hi,

The new UI is better and fine for me.

I improved the logs in the last commit (that is important for a background process: see https://github.com/omeka/Omeka/pull/694/commits/5468deb992980962735f6dd7a0bfd675aa427c0a).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,

@kimisgold 

The new UI is better, but there are bad side effects on all pages that contains buttons + table actions. See the `admin/collections/browse` or `admin/item-types` pages. 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by kimisgold** [comment]
I've provided a fix for the styles by making them specific to items/browse (https://github.com/omeka/Omeka/commit/55f7b23d2a536ed8b5fb16fdb4ac0c537d2d0f60).

**Comment by zerocrates** [comment]
I think we're in agreement that this works well enough that any further work, if any is necessary, can happen on the master branch.
