### ISSUE TITLE
Handle ZF1 EOL

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#720]
We need to make some explicit plans about what we're doing leading up to and after the EOL for ZF1, in terms of maintaining a fork or whatever we come up with.

**Comment by Daniel-KM** [comment]
Hi,

From my point of view, a good solution is to give up Omeka 2, and to propose a full migration path for Omeka S. 

Requirements are not an issue, because a lot of providers already offer php 7, much less cpu and memory intensive for them. Contents and data are already easy to upgrade. Plugins won't be an issue, because main ones are being ported currently. A lot of other ones are not open sourced, so this will be an encouragement to free them, so the communauty can work for them, freely or not (I'll upgrade mine in some weeks). The only difficulty are the themes, but perhaps a simple list of alias for the functions that are in globals.php is enough.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by zerocrates** [comment]
For reference: Zend's planned EOL date is September 28, 2016.

**Comment by sharonmleon** [comment]
Thanks for your thoughts, @Daniel-KM. 

Given the thousands of Omeka Classic (2.x) users and the fact that Omeka S and Omeka Classic don't share any code base or data model, we're not in a position to abandon this version (or the over 40 plugins that we maintain). 

We've made very public promises to users and funders that we will maintain it as an ongoing concern and we will honor those promises.

So, on we go.

Bests,
Sharon

**Comment by Daniel-KM** [comment]
Hi,

Ok, that's clearer.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by zerocrates** [comment]
ZF 1 is officially EOL. We're currently on their last released version.
