### ISSUE TITLE
Update captcha to v2?

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#730]
Looks like ZF1 uses reCaptcha v1, not v2. Should we try to work around ZF to use the new recaptchas?

I see solutions out there to do this, but we'll run into requirement conflicts -- the one's I've looked at so far require a PHP version higher than Omeka's.

**Comment by zerocrates** [comment]
PHP version shouldn't be a problem: Google's own recaptcha 2 code is 5.3.2 and up, same as Omeka.

**Comment by zerocrates** [comment]
Since we already have the captcha code pretty much running through a centralized area of our own, Omeka_Captcha, replacing it with a different implementation probably wouldn't be particularly difficult (though, if anything is doing anything with the returned captcha object and not just using it in a form, that could present a problem).

What I'm not sure about is whether people's current keys would continue to work if we made a change like this. Or, for that matter, whether the v1 will continue to work, as Google has some language on their site implying that new keys from there won't work with v1 anymore. Haven't seen any reports to that effect though.

**Comment by patrickmj** [comment]
When I was tinkering with my keys, I saw a message that universal keys would no longer work with v2 and new keys should be created, so that'll be a thing for some people. But no message that the existing domain-specific keys would break with the version change. Would have to build the change to directly test if that's true.

**Comment by zerocrates** [comment]
There does seem to be a problem with using old "global" keys with the new captcha. (At least, my preexisting key didn't work).

We could either just allow the breakage and tell people to get new keys, or do something like have a setting choosing between the old and the new recaptcha, and default it to the old one.

**Comment by luku** [comment]
Hi, I started to look into this, since the old reCaptcha is unusable. I have found ZF1 lib from [xorock](https://github.com/xorock/ZF1-Google-Recaptcha-v2) that works with the PHP versions Omeka supports (Google's own code requires PHP >= 5.5 in composer.json). But when I started to test [reCaptcha v2](https://developers.google.com/recaptcha/docs/display) and [invisible reCaptcha](https://developers.google.com/recaptcha/docs/invisible), I encountered many browser and functional issues. Just some important ones:
## invisible reCaptcha
- doesn't render well in IE11 and Edge, when badge position is bottom-right/left. In Chrome/Firefox is hard to open Privacy and Terms links when badge position is bottom-right/left.
- page freezes (form inputs are blocked, scrolling works) for at least 30secs in IE11, Edge 
- in Edge console you get lot of errors due to problems with loading font-face ROBOTO
- in Edge: Connection timeout to reCaptcha. Impossible to ever submit anything. More about it [here](https://groups.google.com/forum/#!topic/recaptcha/IW5lTDhkPq4)
- all browsers: When including div for recaptcha, instead of binding it to submit button (which I think is our only option here), it requires JS code for moving reCaptcha token into `g-recaptcha-response` field that will be submitted and then manually submitting form. 

## reCaptcha v2
- page freezes (form inputs are blocked, scrolling works) for at least 30secs in IE11, Edge 
- in Edge console you get lot of errors due to problems with loading font-face ROBOTO
- in Edge: Instead of Connection timeout error, the captcha image(s) are inline, final token must be copied by user into `g-recaptcha-response` text field, but still it's possible to submit the form.

## Conclusion 
From UX point of view and possible Omeka integration, invisible reCaptcha is unusable. reCaptcha v2 is usable and friendly only for users with other browser than IE11 or Edge, so almost as unusable as invisible type.
 
## Alternative?
So I'm thinking if we should offer some alternative? 
1. Honeypot-like trick? Include captcha text field that will be hidden via CSS and validate that it should be empty? Easy to trick.
2. Captcha filled with CSRF-like token via Javascript? Server will generate and store token that will be filled in captcha field via Javascript. Harder to trick, but we cannot use current CSRF tokens for it, so more coding.
3. ??

Any ideas?
