### ISSUE TITLE
Provide Nginx server{} documentation.

### ISSUE THREAD

**Issue by sanguis** [omeka/Omeka#761]
HI All,

I am running Omeka on a LEMP stack as opposed to the documentation that requires Apache.
I was wondering where I can submit a sample of an nginx conf for hosting Omeka?

**Comment by zerocrates** [comment]
Hmmm, that's a good question... Due to spam problems on the wiki, we don't have a lot in the way of explicit spaces for people to share this kind of information with us and each other.

A post on the forums might be best for the time being? It'll be preserved and searchable for people looking for nginx info.

**Comment by sharonmleon** [comment]
@sanguis I'm not sure if you posted your Nginx conf to the forum, but if you haven't yet, we've created a spot for that sort of stuff: https://forum.omeka.org/c/community-contributions
