### ISSUE TITLE
Should get_table_options include translations?

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#832]
Following up on some issues about i18n in ItemRelations, I found that I needed to use a filter to stuff in translatable strings from the DB data that goes to a select form item. See https://github.com/omeka/plugin-ItemRelations/commit/de50c265f46c6e37fd5f299d4f620c58ab1aefce and https://github.com/omeka/plugin-ItemRelations/issues/13

So, should `get_table_options` in core try to do those translations? Or is this special enough that the best practice is just for plugins to do that translation themselves, as in the commit above?

**Comment by zerocrates** [comment]
get_table_options itself does practically nothing. We _could_ add an option there to have it translate the label parts of things automatically though... which could be a good idea. The translation definitions would always need to be coming from elsewhere or be manually included in the template, of course, since these would always be "indirect." These kinds of strings, since they're fetching from the database, are almost always like that anyway, so it's not much of a concern I suppose.

For your current usage you don't need the filter though: the stuff that actually gets used by get_table_options is just the returned data from findPairsForSelectForm, a method that's custom implemented for each table that implements it. So, you could just change that method in Table_ItemRelationsProperty to do the necessary translations.

**Comment by patrickmj** [comment]
Ah. Had not thought of putting in directly in the table. What are the benefits of doing it in the Table class rather than the filter? I s'pose that'd make the i18n changes before plugin filtering. Not sure how valuable that is, though (especially with the thing of plugin order)

**Comment by zerocrates** [comment]
Just seems a little odd to "filter" something the plugin created with its own code elsewhere. It'll also be slightly less efficient but I doubt that makes any significant difference here.

**Comment by patrickmj** [comment]
Makes sense. I'll move things over.

This also exposes that ItemRelations doesn't play nicely with ElementSets from other plugins, but I think that's fine based on the desire for that.

**Comment by zerocrates** [comment]
Does Item Relations use the elements at all?

**Comment by patrickmj** [comment]
Ah. Looks like not. I was confused by the duplication of Dublin Core.

**Comment by patrickmj** [comment]
Turns out that in the case of ItemRelations, a general solution gets tricky because ItemRelations builds up its own select data in a special way that includes subheadings. It's a rare situation, but makes me worry that anything in core could break plugins unexpectedly by trying to do the translations. So, I'm good with those few plugins that need to handling it themselves.
