### ISSUE TITLE
Testing for files/show link option

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#840]
See #759 

This should be working on all themes: the feature is a switch in Appearance Settings that changes where images on the item show page link to: to the file directly (as was the prior default) or to the files/show page.

**Comment by mebrett** [comment]
master branch of all themes?

**Comment by zerocrates** [comment]
sorry yes, latest master of everything

**Comment by mebrett** [comment]
Checkbox is right where it's supposed to be and works depending on the theme. 

No functionality at all for Big Picture, Center Row, or the Daily (expected).

With Seasons and Emilgio, click to see file metadata works for all file types.

For the following themes, it works for all file types *except* media files (audio/video) due to the way av media is displayed. Santa Fe, Berlin, default, minimalist, rhythm

**Comment by zerocrates** [comment]
Yeah presumably the difference is that seasons and emiglio have a "thumbnails only" mode and the others do not.

**Comment by zerocrates** [comment]
Oh, it will also vary for several themes (like default) between if you have the "gallery" theme option turned on or not.

**Comment by mebrett** [comment]
Gallery doesn't seem to make much of a difference in being able to click through for SantaFe, Rhythm, minimalist  - they display a smaller but still playable video box.

For Thanks Roy it does in fact change from a playable video to the generic movie thumbnail. 

On Berlin, having the "click through" checkbox on in Appearance Settings *and* the " " in theme config results in the following error for all media types: `Notice: Undefined variable: linkToFileMetadata in /websites/omekadev/home/www/mebrett/Omeka/themes/berlin/items/show.php on line 6`
