### ISSUE TITLE
User testing for 2.6.1

### ISSUE THREAD

**Issue by zerocrates** [omeka/Omeka#847]
Use master branch

This should just be a case of poking and confirming existing expected behavior:

- the "create API key" UI for a user
- Add Item, Search Items, Quick Filters on items browse (top and bottom, these were both moved slightly in the markup)
- Bottom pagination input on items browse (the direct number entry is broken in 2.6, should be working on master)
- Item form: adding, removing tags
- Item show: sidebar, linking to tags
- Tag browse/edit: renaming, deleting tags, linking to tagged items

Simple Pages, use master
- new "menubar" for editor
- confirm editor checkbox works

**Comment by mebrett** [comment]
Clicking tags in the sidebar of an item/show (on admin side) takes user to the results of a search for items (and only items) with that tag. I'm assuming this is expected behavior?

Two things about editing tags. 
1. Edits *only* take if the user hits return while in the editing field. Clicking outside reverts to the old version. Expected behavior? 
2. Regardless of tag length, clicking to edit renders the field to a specific size - so for longer tags, you end up not being able to see the whole thing. 

![screen shot 2018-05-02 at 10 00 31 am](https://user-images.githubusercontent.com/2314070/39527552-b1f076d8-4def-11e8-89a6-1df655fd3cf9.png)

Checking SimplePages next

**Comment by zerocrates** [comment]
Yeah i don't know what that does exactly either.... but yes, that's what the menu is supposed to look like.

**Comment by zerocrates** [comment]
Looks like it only (or only obviously) takes effect when you have a table in the editor.

**Comment by mebrett** [comment]
So that's what it does. Thanks.
