### ISSUE TITLE
Image/File URLs stored in S3 expose AWS Access Key ID

### ISSUE THREAD

**Issue by maxpearl** [omeka/Omeka#889]
We've successfully used S3 as the back-end file system, but when viewing an image, and clicking through to see the full image, the AWS Access Key ID is exposed in the URL, which looks something like: 
http://s3.amazonaws.com/name-of-s3-bucket/original/c0ffaf8e8ab7cb7bf691cea952734af5.jpg?AWSAccessKeyId=AKOOOOOO999999&Expires=1561662600&Signature=PwPdWaQBjagrUW8VlON2SGFqIA0%3D

In general, this is a very bad security practice. I don't know whether this is an issue with the Zend S3 adaptor, or with how Omeka handles these files, but this is not a good idea.

**Comment by zerocrates** [comment]
That's just what S3 "presigned" URLs look like. We can't vary that format.

If you don't set up the adapter with an "expiration" time it won't use presigned URLs but your objects will be publicly available.

**Comment by maxpearl** [comment]
Ah, I see. That might be worth tweaking the documentation. Currently, the docs say about the expiration setting: 

> If you instead want to have a locked-down access policy, you can set this setting, which will cause Omeka to generate pre-signed URLs for files stored in S3. The effect is that links to files will only be valid for the configured number of minutes after the URL was created.

The problem is, you are actually making things *less* secure, because of the use of presigned URLs when using expirations.

**Comment by zerocrates** [comment]
Hmm, "locked-down access policy" is still pretty much accurate there... really the feature is intended for users concerned chiefly about hotlinking, though it has the side effect that files become totally inaccessible if they don't appear on any public pages (since the necessary signature will not be generated).

The party line has historically been that [access key IDs are not secrets](https://stackoverflow.com/questions/7678835/how-secure-are-amazon-aws-access-keys)
