### ISSUE TITLE
Omeka RSS feed shows private items

### ISSUE THREAD

**Issue by jcmundy** [omeka/Omeka#897]
I am using the RSS feed function in Omeka, which works well, but when I add a new item to the site and leave it private because it is not yet finished, it is still sent out in the RSS feed.  Is there any way to filter the RSS feed so that it shows items once they are checked public rather than when added as private?

**Comment by zerocrates** [comment]
Are you looking at the feed in your browser and seeing private items, or are you seeing them actually come through on a feed reader?

The feed mirrors the browse page: if you're logged in, you'll see private items, including in the feed, but an external visitor and/or their feed reader (and anybody's feed reader, as it doesn't have your session cookie) will only see the stuff they already could otherwise see (in other words, the public items).

**Comment by jcmundy** [comment]
It's been coming in through my feed reader.  I'll get someone else to test it and see if comes in through theirs, or if that's just because it's on my computer.

**Comment by jcmundy** [comment]
Thank you, it was just on my computer.
