### ISSUE TITLE
Duplicate 'active' class in public_nav_items()

### ISSUE THREAD

**Issue by ebellempire** [omeka/Omeka#952]
I'm trying to find a way to control the behavior of the `active` class in the output for `public_nav_items` to find a workaround for the duplication of the `active` class in certain scenarios.

## Description
For example, say I want the secondary navigation for Collections to include "All Collections" and "Featured Collections". This is easy enough and works as expected. I can style the active class to indicate which page is active.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/441279/118010506-1c96cb00-b31d-11eb-9f9e-bfe8a1843140.png">

The problem is when you click on "Featured Collections," they both end up having the active class.
<img width="345" alt="Screen Shot 2021-05-12 at 12 20 34 PM" src="https://user-images.githubusercontent.com/441279/118010734-4f40c380-b31d-11eb-92d1-2e1381f2dc93.png">

Here's the markup:
<img width="524" alt="Screen Shot 2021-05-12 at 12 43 06 PM" src="https://user-images.githubusercontent.com/441279/118012977-a34ca780-b31f-11eb-9799-79e8a9353fd1.png">

The duplicate classes make sense when thinking about common uses like dropdown menus and stuff. But it's a bit of an issue here, where I'm displaying each page inline/horizontally.

## But can't you fix this with CSS?
As far as I can ascertain, there's no valid CSS for controlling that first `.active` element _specifically_ when there is also a second `.active` element, since selectors can only look forward for siblings and not backwards. I've tried a combination of approaches like `:last-child`, `:first-child`, `+`,` ~`, `:last-of-type`, `:first-of-type`, etc. and each is limited in ways that mean I can't really target what I'm looking for. Pretty sure my CSS options have been exhausted. 

## What about JavaScript?
Yes, I can definitely fix this with JavaScript. But it seems sort of ... wrong? 🤷 

## What about PHP?
The only way I can figure to fix this before rendering is to use `substr_count` to determine if there are duplicate `active` classes. This lets me just rewrite the CSS rules for that container class.  
```
$output=public_nav_items($navArray);
$dupeClass = (substr_count($output,'class="active"',0) > 1) ? ' duplicate-actives' : null;     
echo '<nav class="items-nav navigation secondary-nav'.$dupeClass.'">'.$output.'</nav>';
```
Obviously, this is not very efficient. It works but it rubs me wrong (and possibly comes with a little performance hit). There must be a better way. 

## Now what?
I tried looking in the core codebase for solutions/clues but am not finding much from looking at the `public_nav_items` and `nav` functions. I imagine this ultimately gets into Zend stuff, where I tend to get a bit lost. 

Can anyone point me in the right direction?

**Comment by zerocrates** [comment]
The duplication here isn't related to trees or anything like that, it's just down to the ways pages are calculated to be "active." URIs specified as text basically check that the current URI either matches exactly or is a leftmost substring of the current URI. That explains how the `?featured=1` page is correctly "not active" when viewing the main browse.

"MVC" pages just check if the routing parameters of the current page match the ones from the nav entry. This one's the problem here: the link with the query string has the exact same route and routing params as the one without it, so the default link for browsing collections is going to be marked "active" no matter what the query string is (this is generally what we _want_ normally, so the browse continues to show as active when you're doing advanced searches and so on, but it contributes to the problem you're seeing here when you have multiple "versions" of the same page in the nav).

One silly workaround is to have the "main" collections link not be our normal one (which is an "MVC" nav entry) but a manual user-entered URL link, and just specify a nonexistent GET param in the query string. That's enough to make the two links mutually exclusive so they won't both get marked as active.

I don't know that we really have a super feasible way of avoiding the problem in our nav code itself... telling when "duplicate active" or "sloppy active" or whatever you want to call it is desirable and when it's not is tough, and I don't think the Zend Navigation code really has anything useful for us in terms of say, limiting the tree to a single active member. Maybe we could walk it in PHP and manually mark things as "not active"? (I think "activeness" is calculated too late for us to do that, actually).

**Comment by ebellempire** [comment]
Ok, cool. I'll stick with my hacky `substr_count` solution above. Thanks for looking into it!
